spring.h2.console.enabled: true
spring:
  thymeleaf:
    enabled: true

#debug: true
logging:
  level:
    com.amazonaws: info
#    com.amazonaws: trace
    com.amazonaws.xray.spring.aop.AbstractXRayInterceptor: info
#    com.amazonaws.xray.spring.aop.AbstractXRayInterceptor: debug
